### ISSUE TITLE
Windows Issues

### ISSUE THREAD

**Issue by zQueal** [kyoheiu/felix#75]
I don't have an environment conducive to building rust applications. It's possible the file encoding errors that happen under windows has something to do with [this thread](https://cloud.google.com/storage/docs/gsutil/addlhelp/Filenameencodingandinteroperabilityproblems). I would like to test it, but I don't have a windows build.

Anyone willing to build one for me so I can test to see that this works?

**Comment by shirok1** [comment]
I failed to build this crate on Windows because `termion` don't support Windows. There is [a fork by Jezza](https://gitlab.redox-os.org/Jezza/termion/-/tree/windows-support), but the [merge request](https://gitlab.redox-os.org/redox-os/termion/-/merge_requests/151) has been ignored since 3 years ago, and it doesn't support `termion::terminal_size_pixels`. The only reference to it lies in `State::get_sixel_image_preview_size`, which I guess is for displaying image in terminal using `libsixel`? However, common terminals on Windows don't support `libsixel`, so I think corresponding code can be temporarily disabled with `#[cfg(not(target_os = "windows"))]`.

**Comment by kyoheiu** [comment]
@zQueal Sorry for not touching this issue, I don't have a Windows environment.
@shirok1 Thank you for the suggestion. That makes sense, I'll give it a try.

**Comment by zQueal** [comment]
It's my own fault. I really don't know how to cross compile rust applications.

**Comment by kyoheiu** [comment]
Even if felix avoids libsixel use and the call for terminal_size_pixels (92c0bad163c59d9695c52eebd22b14f6c66d93f9), termion cannot be built on Windows and as a consequence the install test on Windows failed (see https://github.com/kyoheiu/felix/actions/runs/2775156733).

Now I wonder how it will work if I choose to use termion Windows support version... It may be worth it, but for now debugging and testing is difficult because I don't have the environment, and other than this issue, there will be a problem around OsString in Windows (it's encoded as utf-16, while Rust String is always utf-8).

**Comment by kyoheiu** [comment]
#93

**Comment by kyoheiu** [comment]
FYI, thanks to the migration from termion to crossterm, the `crossterm` branch can now be compiled on Windows. There may be some bugs though.

**Comment by zQueal** [comment]
Buidling for windows on a linux machine;

```bash
git clone https://github.com/kyoheiu/felix.git
cargo build --target x86_64-pc-windows-gnu
[...]
Some errors have detailed explanations: E0405, E0412, E0433, E0463.
For more information about an error, try `rustc --explain E0405`.
error: could not compile `itoa` due to 43 previous errors
warning: build failed, waiting for other jobs to finish...
```

Tried to build for linux using the same repository;

```bash
cargo build
[...]
Compiling felix v1.2.0 (/tmp/felix)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 09s
```

Seems to still work fine on *nix. 🤷‍♂️

**Comment by kyoheiu** [comment]
Sorry for the ambiguity, please try develop branch (Not merged to main yet)

**Comment by kyoheiu** [comment]
Seems at least Windows build has no issue, so will close this.
