### ISSUE TITLE
Detach from fx

### ISSUE THREAD

**Issue by felixg3** [kyoheiu/felix#76]
Dear @kyoheiu, thank you for creating felix. Foremost, I like the name a lot and I find it very useful and easy to configure. However, would it be possible to implement an option to detach opened windows of imv, mpv, feh, zathura etc. from the running felix application? I can only control felix once I closed the window which I used to view the file.

Thank you!

**Comment by kyoheiu** [comment]
@felixg3 I created a PR to implement this feature #77 , so if you have time could you build from the `new-window` branch and give it a try? In my environment (Arch Linux 
Kernel: 5.17.9-arch1-1 and MacOS 11.6) this feature just works.

To run:
```
git clone https://github.com/kyoheiu/felix.git
cd felix
git checkout new-window
cargo run
```
`cargo install --path .` will also work.
If you configure like `feh = ["jpg"]`, and press `o` on a jpg file, feh will appear in a new window and you can still control felix as well.

Note that if you open a text file with `nvim` for example, no new window appears, item list blank (pressing esc or any key will correct this) and you will get the following error message after exit:
```
Vim: Error reading input, exiting...

Vim: Finished.
```
I think this is because apps like Neovim or vim open files *in* the terminal, and do not consider opening them in a new window.
I'm trying to figure out a way to at least keep the list visible, but would appreciate if you could check out this new feature.

**Comment by kyoheiu** [comment]
Implemented #82

**Comment by felixg3** [comment]
Thank you very much. Unfortunately, I didn’t see your comment until now :( hence I didn’t help/reply. Sorry!

**Comment by kyoheiu** [comment]
@felixg3  Hope this will help you!
