### ISSUE TITLE
Add ueberzug support

### ISSUE THREAD

**Issue by pineapples5972** [kyoheiu/felix#89]
Ueberzug can provide perfect previews for images.
Consider adding using it.

**Comment by kyoheiu** [comment]
Thank you for the suggestion.
Basically I don't want you to install anything other than gcc to use this app.
However, the hi-res preview can't be implemented without runtime dependencies at this moment. In this case, felix uses libsixel and it works fine (if you don't have libsixel, then viuer comes into play). Could you tell me why ueberezug is recommended?

**Comment by pineapples5972** [comment]
[Ueberzug](https://github.com/seebye/ueberzug) draws images on terminal using child windows. 
Here is the difference between libsixel vs ueberzug image previews.
![image](https://user-images.githubusercontent.com/62638787/177521563-e98e89d4-de9a-430f-ba1d-14f762fd552b.png)
In left side felix using libsixel vs In right side vifm using ueberzug.
Vifm and lf does not provide integrated ueberzug support but using these [hacks](https://github.com/pineapples5972/dotfiles/blob/main/.local/bin/vu) users able to get previews working.

**Comment by pineapples5972** [comment]
Sorry my mistake I am using st and it does not support sixel and havent found any patch that works perfectly yet.
but however i have installed wezterm and it renders images good but sixel isnt perfect. It increase load on memory with highres images and it shows grains on images. and cant scroll fast or jumps on different files without lags and slowness but for lessres images its good. 

however its always good to keep our options open. Ueberzug previews are so far light on memory and shows highres images with faster scrolling on files they changes like nothing else.
Consider having a look into it. 
I am no programmer so I can only give suggestions.
meanwhile if you want to check out my experience at terminal images previews with vifm:
 - install ueberzug
 - apply [my vifm config](https://codeberg.org/pineapples/dotfiles/src/branch/main/.config/vifm/vifmrc)
 - and run through [this wrapper script](https://codeberg.org/pineapples/dotfiles/src/branch/main/.local/bin/vu)

**Comment by kyoheiu** [comment]
OK, I'll see how ueberzug works in this app.

**Comment by kyoheiu** [comment]
I've tried ueberzug, and while it surely is faster than libsixel at this moment, I won't introduce it because:
- The license issue. ueberzug is under GPL while felix is MIT, so unless I change the license of felix I cannot use ueberzug either statically or dynamically. And I do not want to change felix's license.
- Though this license issue was apparent from the start, I've tried to implement it inside felix to do my best. However, in the tty mode brought by termion, ueberzug seems not to work correctly. So I think it is at least very difficult to use ueberzug inside felix.
Sorry for those who have expected this.
